name = "pubsub-nim"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "pubsub"
instances = { min = 2, max = 100000, default = 20 }

  [testcases.params]
  connection_count  = { type = "int", desc = "number of connections per node", unit = "nodes", default = 20 }
  publisher_count   = { type = "int", desc = "number of nodes publishing", unit = "nodes", default = 20 }
  message_count     = { type = "int", desc = "number of messages to send per publisher", unit = "msg", default = 20 }
  max_message_delay = { type = "int", desc = "max delay between messages per publisher", unit = "ms", default = 500 }
